from django.db import models
from django.contrib.postgres.fields import ArrayField

class Employee(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(null=True, blank=True)
    is_superuser = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    EMP_code = models.CharField(max_length=10, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    branch_id = ArrayField(models.IntegerField(), null=True, blank=True)
    
    dob = models.DateField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    mother_name = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True)
    hod = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    city_id = models.IntegerField(null=True, blank=True)
    country_id = models.IntegerField(null=True, blank=True)
    department_id = models.IntegerField(null=True, blank=True)
    designation_id = models.IntegerField(null=True, blank=True)
    state_id = models.IntegerField(null=True, blank=True)
    user_role_id = models.IntegerField(null=True, blank=True)
    user_type_id = models.IntegerField(null=True, blank=True)
    pro_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    dispatcher = models.CharField(max_length=50, null=True, blank=True)
    status_id = models.IntegerField(null=True, blank=True)
    fcm_token = models.CharField(max_length=255, null=True, blank=True)
    middle_name = models.CharField(max_length=30, null=True, blank=True)
    secondary_mob_nos = models.CharField(max_length=255, null=True, blank=True)
    ar_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.username
    
    
    
class Employee1(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(null=True, blank=True)
    is_superuser = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    EMP_code = models.CharField(max_length=10, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    branch_id = ArrayField(models.IntegerField(), null=True, blank=True)
    
    dob = models.DateField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    mother_name = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True)
    hod = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    city_id = models.IntegerField(null=True, blank=True)
    country_id = models.IntegerField(null=True, blank=True)
    department_id = models.IntegerField(null=True, blank=True)
    designation_id = models.IntegerField(null=True, blank=True)
    state_id = models.IntegerField(null=True, blank=True)
    user_role_id = models.IntegerField(null=True, blank=True)
    user_type_id = models.IntegerField(null=True, blank=True)
    pro_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    dispatcher = models.CharField(max_length=50, null=True, blank=True)
    status_id = models.IntegerField(null=True, blank=True)
    fcm_token = models.CharField(max_length=255, null=True, blank=True)
    middle_name = models.CharField(max_length=30, null=True, blank=True)
    secondary_mob_nos = models.CharField(max_length=255, null=True, blank=True)
    ar_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.username